apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-deployment
  annotations:
    kubernetes.io/change-cause: "init deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prime-app
  template:
    metadata:
      name: prime-app-template
      labels:
        app: prime-app
        app.kubernetes.io/name: prime-app
    spec:
      containers:
        - name: prime-app
          image: 19122002/prime-image:v1
          ports:
            - containerPort: 3001
              name: http-web-api
          resources:
            requests: 
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: prime-service
spec:
  selector:
    app.kubernetes.io/name: prime-app
  ports:
    - name: "prime-port"
      protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer