apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      name: api-gateway-template
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-container
          image: 19122002/api-gateway
          ports:
            - containerPort: 8888
              name: http-web-api
          resources:
            requests: 
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-app
  ports:
    - name: api-gateway-port
      protocol: TCP
      port: 8888
      targetPort: 8888