apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prime-app
  template:
    metadata:
      name: prime-template
      labels:
        app: prime-app
    spec:
      containers:
        - name: prime-app-container
          image: 19122002/prime-image
          ports:
            - containerPort: 3000
              name: http-web-api
          resources:
            requests: 
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

---

apiVersion: v1 
kind: Service 
metadata: 
  name: prime-service 
spec: 
  type: ClusterIP 
  selector: 
    app: prime-app
  ports: 
    - targetPort: 3000
      port: 3000